---
display_name: Getting Started
sections:
- display_name: What is Spoonium?
  subsections: []
- display_name: Tour I - Hello World
  subsections:
  - display_name: Installation
  - display_name: Get Going
  - display_name: Pull an Image
  - display_name: Create a Container
  - display_name: Creating Files within a Container
- display_name: Tour II - A Web Application
  subsections:
  - display_name: Topics Covered
  - display_name: Create a Ghost Image
  - display_name: Running the Ghost Web Application
  - display_name: Running Multiple Instances
  - display_name: Saving a Database to a Layer
  - display_name: Reverting the Container
  - display_name: Pulling It All Together
- display_name: Tour III - Automated Testing
  subsections:
  - display_name: Next Steps
- display_name: Installation
  subsections:
  - display_name: Windows
  - display_name: Azure
  - display_name: EC2
- display_name: About
  subsections:
  - display_name: Virtual Machine
  - display_name: Containers
  - display_name: Images
  - display_name: Hub
  - display_name: IDE and Command Line
  - display_name: Spoon Server
---
display_name: Hub
sections:
- display_name: Creating a Profile
  subsections: []
- display_name: Repositories
  subsections: []
- display_name: Templates
  subsections: []
---
display_name: Building
sections:
- display_name: Working with Containers
  subsections:
  - display_name: Creating Containers
  - display_name: Managing Containers
  - display_name: Processes and Stopping Containers
  - display_name: Debugging
  - display_name: Building Images from Containers
- display_name: Working with Images
  subsections:
  - display_name: Creating Images
  - display_name: Forking, Renaming, and Tagging
  - display_name: Push to a Remote Repository
- display_name: Working with the IDE
  subsections: []
- display_name: Desktop Scan
  subsections:
  - display_name: Running a Desktop Scan
  - display_name: Best Practices
  - display_name: Troubleshooting
- display_name: Snapshotting
  subsections:
  - display_name: Process
  - display_name: Capture Application Updates via Snapshot
  - display_name: Best Practices
- display_name: Continuous Integration
  subsections:
  - display_name: Create SpoonScript
  - display_name: Integrate into the CI Server
  - display_name: Run the container
---
display_name: Testing
sections:
- display_name: Manual Browser Testing
  subsections: []
- display_name: Selenium Testing
  subsections:
  - display_name: Debugging Tests
  - display_name: Integrating Spoonium with an Existing Grid
  - display_name: Testing Internal Sites
  - display_name: Testing Internet Explorer
  - display_name: Common Issues and Troubleshooting
- display_name: JS Unit Testing
  subsections:
  - display_name: Getting Started - Karma
  - display_name: Getting Started - Mocha/Mochify
- display_name: Test Reports
  subsections: []
- display_name: Testing with CI
  subsections: []
- display_name: Nightly Builds (coming soon)
  subsections: []
---
display_name: Deploying
sections:
- display_name: To the Hub
  subsections: []
- display_name: To Spoon.net
  subsections: []
- display_name: To a Spoon Server
  subsections: []
- display_name: Portable EXE
  subsections: []
- display_name: MSI
  subsections: []
- display_name: Shell Registration
  subsections: []
---
display_name: Reference
sections:
- display_name: Command Line
  subsections:
  - display_name: help
  - display_name: build
  - display_name: checkout
  - display_name: commit
  - display_name: config
  - display_name: containers
  - display_name: cp
  - display_name: diff
  - display_name: export
  - display_name: fork
  - display_name: history
  - display_name: images
  - display_name: import
  - display_name: login
  - display_name: logout
  - display_name: logs
  - display_name: netstat
  - display_name: pause
  - display_name: ps
  - display_name: pull
  - display_name: push
  - display_name: register
  - display_name: resume
  - display_name: revert
  - display_name: rm
  - display_name: rmi
  - display_name: run
  - display_name: search
  - display_name: start
  - display_name: tag
  - display_name: unregister
  - display_name: version
  - display_name: vm
  - display_name: vms
- display_name: IDE
  subsections:
  - display_name: Virtual Filesystem
  - display_name: Virtual Registry
  - display_name: Runtimes and Components
- display_name: SpoonScript
  subsections:
  - display_name: cmd
  - display_name: disable
  - display_name: enable
  - display_name: env
  - display_name: from
  - display_name: hosts
  - display_name: meta
  - display_name: route
  - display_name: startup file
  - display_name: using
  - display_name: workdir
- display_name: XAPPL
  subsections: []
- display_name: Virtual Application Settings
  subsections: []
- display_name: MSI Settings
  subsections: []
- display_name: VM Settings
  subsections: []
- display_name: Samples
  subsections:
  - display_name: Java
  - display_name: Node.js
  - display_name: .NET
  - display_name: Python
---
display_name: Contributing
sections:
- display_name: Contribute to Spoonium
  subsections: []
- display_name: Style Guide
  subsections: []