---
display_name: Getting Started
ordering: 1
sections:
- display_name: What is Spoonium?
  ordering: 1
  pages: []
  subsections: []
- display_name: Tour I - Hello World
  ordering: 2
  pages: []
  subsections: []
- display_name: Tour II - A Web Application
  ordering: 3
  pages: []
  subsections: []
- display_name: Tour III - Automated Testing
  ordering: 4
  pages: []
  subsections: []
- display_name: Installation
  ordering: 5
  pages: []
  subsections: []
- display_name: About
  ordering: 6
  pages: []
  subsections: []
---
display_name: Hub
ordering: 2
sections:
- display_name: Creating a Profile
  ordering: 1
  pages: []
  subsections: []
- display_name: Repositories
  ordering: 2
  pages: []
  subsections: []
- display_name: Templates
  ordering: 3
  pages: []
  subsections: []
---
display_name: Building
ordering: 3
sections:
- display_name: Working with Containers
  ordering: 1
  pages: []
  subsections: []
- display_name: Working with Images
  ordering: 2
  pages: []
  subsections: []
- display_name: Working with the IDE
  ordering: 3
  pages: []
  subsections: []
- display_name: Desktop Scan
  ordering: 4
  pages: []
  subsections: []
- display_name: Snapshotting
  ordering: 5
  pages: []
  subsections: []
- display_name: Continuous Integration
  ordering: 6
  pages: []
  subsections: []
---
display_name: Testing
ordering: 4
sections:
- display_name: Manual Browser Testing
  ordering: 1
  pages: []
  subsections: []
- display_name: Selenium Testing
  ordering: 2
  pages: []
  subsections: []
- display_name: JS Unit Testing
  ordering: 3
  pages: []
  subsections: []
- display_name: Test Reports
  ordering: 4
  pages: []
  subsections: []
- display_name: Testing with CI
  ordering: 5
  pages: []
  subsections: []
- display_name: Nightly Builds (coming soon)
  ordering: 6
  pages: []
  subsections: []
---
display_name: Deploying
ordering: 5
sections:
- display_name: To the Hub
  ordering: 1
  pages: []
  subsections: []
- display_name: To Spoon.net
  ordering: 2
  pages: []
  subsections: []
- display_name: To a Spoon Server
  ordering: 3
  pages: []
  subsections: []
- display_name: Portable EXE
  ordering: 4
  pages: []
  subsections: []
- display_name: MSI
  ordering: 5
  pages: []
  subsections: []
- display_name: Shell Registration
  ordering: 6
  pages: []
  subsections: []
---
display_name: Reference
ordering: 6
sections:
- display_name: Command Line
  ordering: 1
  pages: []
  subsections:
  - display_name: help
    ordering: 1
  - display_name: build
    ordering: 2
  - display_name: checkout
    ordering: 3
  - display_name: commit
    ordering: 4
  - display_name: config
    ordering: 5
  - display_name: containers
    ordering: 6
  - display_name: cp
    ordering: 7
  - display_name: diff
    ordering: 8
  - display_name: export
    ordering: 9
  - display_name: fork
    ordering: 10
  - display_name: history
    ordering: 11
  - display_name: images
    ordering: 12
  - display_name: import
    ordering: 13
  - display_name: login
    ordering: 14
  - display_name: logout
    ordering: 15
  - display_name: logs
    ordering: 16
  - display_name: netstat
    ordering: 17
  - display_name: pause
    ordering: 18
  - display_name: ps
    ordering: 19
  - display_name: pull
    ordering: 20
  - display_name: push
    ordering: 21
  - display_name: register
    ordering: 22
  - display_name: resume
    ordering: 23
  - display_name: revert
    ordering: 24
  - display_name: rm
    ordering: 25
  - display_name: rmi
    ordering: 26
  - display_name: run
    ordering: 27
  - display_name: search
    ordering: 28
  - display_name: start
    ordering: 29
  - display_name: tag
    ordering: 30
  - display_name: unregister
    ordering: 31
  - display_name: version
    ordering: 32
  - display_name: vm
    ordering: 33
  - display_name: vms
    ordering: 34
- display_name: IDE
  ordering: 2
  pages: []
  subsections: []
- display_name: SpoonScripts
  ordering: 3
  pages: []
  subsections: []
- display_name: XAPPL
  ordering: 4
  pages: []
  subsections: []
- display_name: Virtual Application Settings
  ordering: 5
  pages: []
  subsections: []
- display_name: MSI Settings
  ordering: 6
  pages: []
  subsections: []
- display_name: VM Settings
  ordering: 7
  pages: []
  subsections: []
- display_name: Samples
  ordering: 8
  pages: []
  subsections: []