---
display_name: Quick Start
ordering: 1
sections:
- display_name: What is Spoonium?
  ordering: 1
  pages: []
- display_name: Tour I - Hello World
  ordering: 2
  pages: []
- display_name: Tour II - A Web Application
  ordering: 3
  pages: []
- display_name: Tour III - Automated Testing
  ordering: 4
  pages: []
---
display_name: About
ordering: 2
sections:
- display_name: Virtual Machine
  ordering: 1
  pages: []
- display_name: Containers
  ordering: 2
  pages: []
- display_name: Images
  ordering: 3
  pages: []
- display_name: IDE and Command Line
  ordering: 4
  pages: []
- display_name: Hub
  ordering: 5
  pages: []
- display_name: Spoon Server
  ordering: 6
  pages: []
---
display_name: Installation
ordering: 3
sections:
- display_name: Windows
  ordering: 1
  pages: []
- display_name: EC2 (coming soon)
  ordering: 2
  pages: []
- display_name: Azure (coming soon)
  ordering: 3
  pages: []
---
display_name: Hub
ordering: 4
sections:
- display_name: Creating a Profile
  ordering: 1
  pages: []
- display_name: Registries
  ordering: 2
  pages: []
- display_name: Repositories
  ordering: 3
  pages: []
- display_name: Templates
  ordering: 4
  pages: []
---
display_name: Build
ordering: 5
sections:
- display_name: Working with Containers
  ordering: 1
  pages: []
- display_name: Working with Images
  ordering: 2
  pages: []
- display_name: Working with the IDE
  ordering: 3
  pages: []
- display_name: Desktop Scan
  ordering: 4
  pages: []
- display_name: Snapshotting
  ordering: 5
  pages: []
- display_name: Continuous Integration
  ordering: 6
  pages: []
---
display_name: Test
ordering: 6
sections:
- display_name: Manual Browser Testing
  ordering: 1
  pages: []
- display_name: Selenium Testing
  ordering: 2
  pages: []
- display_name: JS Unit Testing
  ordering: 3
  pages: []
- display_name: Test Reports
  ordering: 4
  pages: []
- display_name: Testing with CI
  ordering: 5
  pages: []
- display_name: Nightly Builds (coming soon)
  ordering: 6
  pages: []
---
display_name: Deploy
ordering: 7
sections:
- display_name: To the Hub
  ordering: 1
  pages: []
- display_name: To Spoon.net
  ordering: 2
  pages: []
- display_name: To a Spoon Server
  ordering: 3
  pages: []
- display_name: Portable EXE
  ordering: 4
  pages: []
- display_name: MSI
  ordering: 5
  pages: []
- display_name: Shell Registration
  ordering: 6
  pages: []
---
display_name: Samples
ordering: 8
sections:
- display_name: Java
  ordering: 1
  pages: []
- display_name: Node.js
  ordering: 2
  pages: []
- display_name: .NET
  ordering: 3
  pages: []
- display_name: Python
  ordering: 4
  pages: []
---
display_name: Reference
ordering: 9
sections:
- display_name: Command Line
  ordering: 1
  pages: []
- display_name: IDE
  ordering: 2
  pages: []
- display_name: Spoon Scripts
  ordering: 3
  pages: []
- display_name: XAPPL
  ordering: 4
  pages: []
- display_name: Virtual Application Settings
  ordering: 5
  pages: []
- display_name: MSI Settings
  ordering: 6
  pages: []
- display_name: VM Settings
  ordering: 7
  pages: []